"""control plane: rag_sets, documents, imports, jobs

Revision ID: 26fbc5067215
Revises: 
Create Date: 2026-08-27 17:34:29.757099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26fbc5067215'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('temperature', sa.Float(), server_default=sa.text('0.3'), nullable=False),
    sa.Column('top_k', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('score_threshold', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('icon_key', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('score_threshold >= 0 AND score_threshold <= 1', name='ck_rag_score_threshold'),
    sa.CheckConstraint('temperature >= 0 AND temperature <= 1', name='ck_rag_temperature'),
    sa.CheckConstraint('top_k >= 1 AND top_k <= 10', name='ck_rag_top_k'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rag_sets_owner_alive', 'rag_sets', ['owner_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_rag_sets_owner_name', 'rag_sets', ['owner_id', sa.literal_column('lower(name)')], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('import_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rag_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('documents_total', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('documents_created', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('documents_skipped', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kind IN ('archive','s3')", name='ck_batch_kind'),
    sa.ForeignKeyConstraint(['rag_id'], ['rag_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_import_batches_rag', 'import_batches', ['rag_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rag_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('origin', sa.String(length=16), server_default=sa.text("'upload'"), nullable=False),
    sa.Column('origin_ref', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('chunks_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("origin IN ('upload','archive','s3')", name='ck_document_origin'),
    sa.CheckConstraint("status IN ('pending','processing','success','failed')", name='ck_document_status'),
    sa.ForeignKeyConstraint(['origin_ref'], ['import_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rag_id'], ['rag_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rag_id', 'content_hash', name='uq_documents_rag_hash')
    )
    op.create_index('ix_documents_rag_status', 'documents', ['rag_id', 'status'], unique=False)
    op.create_table('ingest_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('rq_job_id', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingest_jobs_document', 'ingest_jobs', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ingest_jobs_document', table_name='ingest_jobs')
    op.drop_table('ingest_jobs')
    op.drop_index('ix_documents_rag_status', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_import_batches_rag', table_name='import_batches')
    op.drop_table('import_batches')
    op.drop_index('uq_rag_sets_owner_name', table_name='rag_sets', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_rag_sets_owner_alive', table_name='rag_sets', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('rag_sets')
    # ### end Alembic commands ###
