"""documents.source_bucket, origin=bucket

Revision ID: 557f3078bc28
Revises: 26fbc5067215
Create Date: 2026-09-23 14:36:31.497607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '557f3078bc28'
down_revision: Union[str, Sequence[str], None] = '26fbc5067215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('source_bucket', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'source_bucket')
    # ### end Alembic commands ###
